# compose.yaml
services:
  container-final:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    image: saoyui/s7container:latest
    container_name: s7container
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - .:/home/adevuser/workspace
      - ${WEZTERM_UNIX_SOCKET:-dummy_volume}:/tmp/wezterm.sock
    working_dir: /home/adevuser/workspace
    restart: unless-stopped

volumes:
  dummy_volume:
