build:
	bash cmd/build.sh

start:
	bash cmd/start.sh

stop:
	bash cmd/stop.sh

conn:
	bash cmd/conn.sh

push:
	bash cmd/push.sh

base/build-again.sh:
	bash cmd/base/build-again.sh

devcontainer:
	bash cmd/devcontainer/__init__.sh

devcontainer/down:
	bash cmd/devcontainer/down.sh
