build:
	bash cmd/build.sh

start:
	bash cmd/start.sh

stop:
	bash cmd/stop.sh

conn:
	bash cmd/conn.sh

# Base -------------------------------------------------------------------------

base/push:
	bash cmd/push.sh base

base/build-again:
	bash cmd/build-again.sh base

# Dev --------------------------------------------------------------------------

dev/push:
	bash cmd/push.sh dev

dev/build-again:
	bash cmd/build-again.sh dev

# Devcontainer -----------------------------------------------------------------

devcontainer:
	bash cmd/devcontainer/__init__.sh

devcontainer/down:
	bash cmd/devcontainer/down.sh
