build:
	bash cmd/build.sh

start:
	bash cmd/start.sh

stop:
	bash cmd/stop.sh

conn:
	bash cmd/conn.sh

push:
	bash cmd/push.sh

base-build:
	bash cmd/base/build.sh

base-stop:
	bash cmd/base/stop.sh
