#!/bin/bash

set -euo pipefail

source docker/env.sh

sudo \
  CONFIG_PROJECT_NAME="$CONFIG_PROJECT_NAME" \
  CONFIG_ENV_XDG_RUNTIME_DIR="$CONFIG_ENV_XDG_RUNTIME_DIR" \
  CONFIG_ENV_WAYLAND_DISPLAY="$CONFIG_ENV_WAYLAND_DISPLAY" \
  CONFIG_FROM_WAYLAND_SOCKET="$CONFIG_FROM_WAYLAND_SOCKET" \
  CONFIG_TO_WAYLAND_SOCKET="$CONFIG_TO_WAYLAND_SOCKET" \
  CONFIG_FROM_WEZTERM_SOCKET="$CONFIG_FROM_WEZTERM_SOCKET" \
  CONFIG_TO_WEZTERM_SOCKET="$CONFIG_TO_WEZTERM_SOCKET" \
  "$@"
