name: ${CONFIG_PROJECT_NAME}
services:
  app:
    extends:
      file: ${CONFIG_CONTEXT}/projects/docker/compose.yaml
      service: app
    image: ${CONFIG_IMAGE}
    build:
      target: base
      args:
        CONFIG_USER_NAME: ${CONFIG_USER_NAME}
        CONFIG_XDG_RUNTIME_DIR: ${CONFIG_XDG_RUNTIME_DIR}
    volumes:
      - ${CONFIG_MOUNT_S7ISOL:-$CONFIG_MOUNT_FALLBACK}
