name: ${CONFIG_PROJECT_NAME}_deploy
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
      target: deploy
      args:
        CONFIG_USER_NAME: ${CONFIG_USER_NAME}
        CONFIG_WORKSPACE: ${CONFIG_WORKSPACE}
        CONFIG_ENV_XDG_RUNTIME_DIR: ${CONFIG_ENV_XDG_RUNTIME_DIR}
    image: saoyui/s7container-base:latest
