# hadolint ignore=DL3007
FROM archlinux:latest AS base

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

# Avoid naming CONFIG_USERNAME or CONFIG_PASSWORD
ARG CONFIG_USER_NAME

# ------------------------------------------------------------------------------
COPY . /mnt/s7isol
WORKDIR /mnt/s7isol
RUN bash setup/root-create-user.sh \
  --username ${CONFIG_USER_NAME} \
  --password ${CONFIG_USER_NAME} \
  --home
USER 1000
RUN bash user.sh

# ==============================================================================
ARG CONFIG_XDG_RUNTIME_DIR
RUN mkdir -p "${CONFIG_XDG_RUNTIME_DIR}"
