FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive

# Create workspace directory
RUN mkdir -p /workspace
WORKDIR /workspace
COPY . .

# Install development tools
RUN bash ./scripts/docker/__init__.sh

EXPOSE 22

ENTRYPOINT ["bash", "./scripts/docker/main.sh"]
