FROM ubuntu:26.04

ENV DEBIAN_FRONTEND=noninteractive

RUN mkdir -p /workspace
WORKDIR /workspace
COPY . .

RUN bash ./scripts/docker/root/__init__.sh

USER adevuser

RUN bash ./scripts/docker/user.sh

EXPOSE 22

ENTRYPOINT ["bash", "./scripts/docker/start.sh"]
