[project]
name = "projects"
requires-python = "==3.14.*"
version = "0"
dependencies = [
  # Configs --------------------------------------------------------------------
  "pydantic",
  "pyyaml",
  "dotenv",

  # Logging --------------------------------------------------------------------
  "loguru",
  # "tqdm",

  # Ui -------------------------------------------------------------------------
  "pyside6",

  # Networking -----------------------------------------------------------------
  # "fastapi",
  # "python-multipart",
  # "requests",
  # "uvicorn",

  # Databases ------------------------------------------------------------------
  # "pymongo",

  # Multimedia -----------------------------------------------------------------
  # "opencv-python-headless",

  # Machine learning -----------------------------------------------------------
  # "matplotlib",
  # "scikit-learn",
  # "torch",

  # GPU ------------------------------------------------------------------------
  # "nvidia-cublas",
  # "nvidia-cuda-runtime",
  # "nvidia-cudnn-cu13",
  # "nvidia-cufft",
  # "nvidia-curand",
  # "nvidia-cusolver",
  # "nvidia-cusparse",
  # "nvidia-cuda-nvcc",
]

[tool.uv]
package = false
