#!/bin/bash

set -euo pipefail

CONFIG_PROJECT_NAME="s7dev"

# Wayland ----------------------------------------------------------------------

CONFIG_HOST_XDG_RUNTIME_DIR="${XDG_RUNTIME_DIR:-"/run/user/$(id -u)"}"
CONFIG_ENV_XDG_RUNTIME_DIR="/home/adevuser/sockets"
CONFIG_ENV_WAYLAND_DISPLAY="${WAYLAND_DISPLAY:-}"

CONFIG_FROM_WAYLAND_SOCKET="$CONFIG_HOST_XDG_RUNTIME_DIR/$CONFIG_ENV_WAYLAND_DISPLAY"
CONFIG_TO_WAYLAND_SOCKET="$CONFIG_ENV_XDG_RUNTIME_DIR/${CONFIG_ENV_WAYLAND_DISPLAY:-"wayland-0"}"

if [[ ! -S "$CONFIG_FROM_WAYLAND_SOCKET" ]]; then
  CONFIG_FROM_WAYLAND_SOCKET="dummy_volume"
fi

# Wezterm ----------------------------------------------------------------------

CONFIG_FROM_WEZTERM_SOCKET="${WEZTERM_UNIX_SOCKET:-}"
CONFIG_TO_WEZTERM_SOCKET="$CONFIG_ENV_XDG_RUNTIME_DIR/wezterm.sock"

if [[ ! -S "$CONFIG_FROM_WEZTERM_SOCKET" ]]; then
  CONFIG_FROM_WEZTERM_SOCKET="dummy_volume"
fi

# ------------------------------------------------------------------------------

sudo \
  CONFIG_PROJECT_NAME="$CONFIG_PROJECT_NAME" \
  CONFIG_ENV_XDG_RUNTIME_DIR="$CONFIG_ENV_XDG_RUNTIME_DIR" \
  CONFIG_ENV_WAYLAND_DISPLAY="$CONFIG_ENV_WAYLAND_DISPLAY" \
  CONFIG_FROM_WAYLAND_SOCKET="$CONFIG_FROM_WAYLAND_SOCKET" \
  CONFIG_TO_WAYLAND_SOCKET="$CONFIG_TO_WAYLAND_SOCKET" \
  CONFIG_FROM_WEZTERM_SOCKET="$CONFIG_FROM_WEZTERM_SOCKET" \
  CONFIG_TO_WEZTERM_SOCKET="$CONFIG_TO_WEZTERM_SOCKET" \
  "$@"
